import os

class ATPCaseBuilder:
    def __init__(self, template_path: str = None):
        self.template_path = template_path

    def build(self, operating_point, hidden_network, event, output_path: str) -> str:
        """
        Translates steady-state operating point, network configuration, and event
        into an ATP card syntax (.ATP format), and writes it to output_path.
        """
        atp_lines = [
            "C  ATP Case File Generated by Python Driver",
            "C  =========================================",
            f"C  Pre-event voltage (pu): {operating_point.voltage_pu.get('transformer1', 1.0):.4f}",
            f"C  Pre-event frequency (Hz): {operating_point.frequency_hz:.2f}",
            f"C  Event Type: {event.event_type}",
            f"C  Event Target: {event.target}",
            f"C  Event Start Time: {event.start_time_s} s",
            "C  -----------------------------------------",
            "BEGIN CARBON COUPLING CARDS",
            "33-kV Source: impedance equivalent",
            "Transformer: 33/11-kV 7.5 MVA Dyn11",
            "  Leakage Reactance: 8.33 pu",
            "  No-Load Loss: 7.5 kW",
            "  Copper Loss: 50.0 kW",
            f"  Secondary Bus load: {operating_point.feeder_p_kw.get('feeder1', 1000.0):.2f} kW",
            "END CARBON COUPLING CARDS",
            f"SWITCH ON {event.target} AT TIME {event.start_time_s}"
        ]

        atp_content = "\n".join(atp_lines)
        if output_path:
            os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
            with open(output_path, "w") as f:
                f.write(atp_content)
        return atp_content
