import os

class ATPCaseBuilder:
    def __init__(self, template_path: str = None):
        self.template_path = template_path

    def build(self, realization, operating_point, event, output_path: str) -> str:
        """
        Translates steady-state operating point, NetworkRealization, and event
        into an ATP card syntax (.ATP format), and writes it to output_path.
        """
        scenario_id = realization.scenario_id
        lines = realization.topology.get("lines", [])
        loads = realization.loads.get("loads", [])
        capacitors = realization.loads.get("capacitors", [])

        event_type = getattr(event, "event_type", "no_event")
        event_target = getattr(event, "target", "")
        event_start = getattr(event, "start_time_s", 0.02)
        event_duration = getattr(event, "duration_s", 0.04)

        atp_lines = [
            "C  ATP Case File Generated by Python Driver",
            "C  =========================================",
            f"C  Realization ID: {scenario_id}",
            f"C  Pre-event voltage (pu): {operating_point.voltage_pu.get('transformer1', 1.0):.4f}",
            f"C  Pre-event frequency (Hz): {operating_point.frequency_hz:.2f}",
            f"C  Event Type: {event_type}",
            f"C  Event Target: {event_target}",
            f"C  Event Start Time: {event_start} s",
            f"C  Event Duration: {event_duration} s",
            "C  -----------------------------------------",
            "BEGIN CARBON COUPLING CARDS",
            "33-kV Source: impedance equivalent"
        ]

        # Serialize the network lines into the ATP card
        for ln in lines:
            atp_lines.append(f"LINE CARD: {ln['name']} bus1={ln['bus1']} bus2={ln['bus2']} length={ln['length']}")

        # Serialize loads
        for ld in loads:
            atp_lines.append(f"LOAD CARD: {ld['name']} bus1={ld['bus']} kw={ld['kw']} pf={ld['pf']} model={ld['model']}")

        # Serialize capacitors
        for cap in capacitors:
            atp_lines.append(f"CAPACITOR CARD: {cap['name']} bus1={cap['bus']} kvar={cap['kvar']}")

        atp_lines.append("END CARBON COUPLING CARDS")
        atp_lines.append(f"SWITCH ON {event_target} AT TIME {event_start}")

        atp_content = "\n".join(atp_lines)
        if output_path:
            os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
            with open(output_path, "w") as f:
                f.write(atp_content)
        return atp_content
