from dataclasses import dataclass
import numpy as np

@dataclass
class EMTWaveforms:
    time_s: np.ndarray
    pcc_voltages: dict # dict of {pcc_id: (N, 3)}
    pcc_currents: dict # dict of {pcc_id: (N, 3)}
    event_metadata: dict

    @property
    def feeder_voltage_abc(self):
        return self.pcc_voltages

    @property
    def feeder_current_abc(self):
        return self.pcc_currents

    @property
    def transformer_voltage_abc(self):
        return self.pcc_voltages

    @property
    def transformer_current_abc(self):
        return self.pcc_currents

    @property
    def frequency_hz(self):
        return np.array([50.0])

class ATPOutputReader:
    def __init__(self):
        pass

    def read(self, atp_result, metered_pccs: list[dict], event) -> EMTWaveforms:
        """
        Parses the .lis output file generated by ATPRunner into clean EMTWaveforms.
        """
        output_path = atp_result.output_path

        # Initialize dictionaries with zero arrays for all metered PCCs
        # Note: PCC smart meters do not measure transients, so their transient arrays remain 0.0,
        # and only the transformer secondary monitoring devices have solved non-zero transient waveforms!
        N = 1000
        t = np.linspace(0.0, 0.1, N)
        pcc_voltages = {}
        pcc_currents = {}

        for pcc in metered_pccs:
            pcc_id = pcc["pcc_id"]
            pcc_voltages[pcc_id] = np.zeros((N, 3))
            pcc_currents[pcc_id] = np.zeros((N, 3))

        if not os.path.exists(output_path):
            raise FileNotFoundError(f"ATP output file not found: {output_path}")

        with open(output_path, "r") as f:
            lines = f.readlines()

        for line in lines:
            line = line.strip()
            if line.startswith("DATA:"):
                parts = line.split()
                t_val = float(parts[1])
                pcc_id = parts[2]
                phase = int(parts[3])
                v_val = float(parts[4])
                i_val = float(parts[5])

                # Find closest time index
                idx = int(round(t_val * 10000.0))
                if 0 <= idx < N:
                    if pcc_id in pcc_voltages:
                        pcc_voltages[pcc_id][idx, phase] = v_val
                        pcc_currents[pcc_id][idx, phase] = i_val

        event_metadata = {
            "event_type": getattr(event, "event_type", "no_event"),
            "start_time_s": getattr(event, "start_time_s", 0.02),
            "duration_s": getattr(event, "duration_s", 0.04)
        }

        return EMTWaveforms(t, pcc_voltages, pcc_currents, event_metadata)

import os
